name: Build DS9490R-OWFS release

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to DockerHub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build docker container and push
                id: docker_build
                uses: docker/build-push-action@v2
                with:
                    context: ./busmaster
                    file: ./busmaster/Dockerfile
                    platforms: linux/amd64,linux/arm/v7,linux/arm64
                    push: true
                    tags: |
                        pharndt/ds9490r-owfs:latest
                        pharndt/ds9490r-owfs:1.0.${{ github.run_number }}

            -   name: Create Release
                id: create_release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: '1.0.${{ github.run_number }}-ds9490r'
                    release_name: DS9490R-OWFS Release 1.0.${{ github.run_number }}
                    body: |
                        Docker tag:
                          pharndt/ds9490r-owfs:1.0.${{ github.run_number }}

                        Changes in this Release
                          - ...

                    draft: false
                    prerelease: true
